menu:
    Home: https://nginxunit.cn
    Post: /
    Archive: /archives/
#    Weibo: http://weibo.com/sunchongsheng
#    GitHub: https://github.com/pinggod
    Rss: /atom.xml

favicon: /nginx-favicon.png
logo: /nginx-favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x
baidu_tongji: 9937dd73aee0d93c796e9f42a92b971a

# Copyright Infomation
startyear: 2017
